- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - common

- hosts: master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - master

- hosts: nodes
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - nodes 
#    - prepare_disks
