- name: iptables key
  command: iptables -N SWIFT

- name: iptables 24007
  command: iptables -A SWIFT -p tcp -m state --state NEW -m tcp --dport 24007 -j ACCEPT

- name: iptables 24008
  command: iptables -A SWIFT -p tcp -m state --state NEW -m tcp --dport 24008 -j ACCEPT

- name: iptables 2222
  command: iptables -A SWIFT -p tcp -m state --state NEW -m tcp --dport 2222 -j ACCEPT

- name: iptables 49152
  command: iptables -A SWIFT -p tcp -m state --state NEW -m multiport --dports 49152:49251 -j ACCEPT

- name: join with master
  command: kubeadm join --token={{ kubernetes_token }} {{ hostvars['master'].ansible_eth1.ipv4.address }}:6443

#route add 10.96.0.1 gw 10.30.3.41
- name: save iptables
  command: service iptables save
