- name: install cloud sig
  package: name=centos-release-openstack-ocata state=present
  
- name: install utility programs
  yum: name={{ item }} state=present
  with_items:
    - python-swift
    - python2-swiftclient

- name: set correct terminal in bashrc
  lineinfile:
      dest: /home/vagrant/.bashrc
      regexp: '^export TERM='
      line: 'export TERM=xterm'

- name: set correct editor in bashrc
  lineinfile:
      dest: /home/vagrant/.bashrc
      regexp: '^export EDITOR='
      line: 'export EDITOR=vim'

- name: set kubectl alias in bashrc
  lineinfile:
      dest: /home/vagrant/.bashrc
      regexp: '^alias kk='
      line: 'alias kk=kubectl'

- name: create
  command: kubeadm init --token={{ kubernetes_token }} --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}
  
- name: copy admin.conf
  command: cp /etc/kubernetes/admin.conf /home/vagrant/

- name: configure permissions for admin.conf
  command: chown vagrant:vagrant /home/vagrant/admin.conf

- name: set correct editor in bashrc
  lineinfile:
      dest: /home/vagrant/.bashrc
      line: 'export KUBECONFIG=$HOME/admin.conf'


- name: create cluster network
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f {{ kubeadm_network_addon_url }}

#- name: create cluster network - flannel rbac
#  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f {{ item }}
#  with_items:
#    - https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
#    - https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: get dns service address
  shell: kubectl --kubeconfig /etc/kubernetes/admin.conf get services --all-namespaces | grep kube-dns | awk "{print \$3}"
  register: kubednsaddress

- name: wait for dns to be ready
  wait_for: host={{ kubednsaddress.stdout }} port=53 state=started timeout=1800

- name: save iptables
  command: service iptables save
